version: '3'

services:

  nats-server:
    image: nats:latest

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/nestjs-microservices-421221/image-registry/client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment: 
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/nestjs-microservices-421221/image-registry/auth-ms-prod
    environment: 
      - PORT=${AUTH_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/nestjs-microservices-421221/image-registry/products-ms-prod
    environment: 
      - PORT=3001
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: europe-southwest1-docker.pkg.dev/nestjs-microservices-421221/image-registry/orders-ms-prod
    environment: 
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/nestjs-microservices-421221/image-registry/payments-ms-prod
    ports:
      - ${PAYMENTS_PORT}:${PAYMENTS_PORT}
    environment: 
      - PORT=${PAYMENTS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${PAYMENTS_STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENTS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET_TEST=${PAYMENTS_STRIPE_ENDPOINT_SECRET_TEST}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_STRIPE_ENDPOINT_SECRET}